### PR TITLE
GH-22: added separate folder to maintain Apache2 conf files

### PR DESCRIPTION
**Pull request by danehrlich1**
Beginning of pull request. Still have more to add. Thought this was a good beginning.

### CODE REVIEW

**Comment by danehrlich1** [comment]
- [ ] 1. Update `security.conf` with as many security options as will still allow the proxy to work
- [ ] 2. Do similar for `Apache2.conf`
- [ ] 3. Make sure to set up correct SSL parameters (there are many) in `default-ssl.conf`
- [ ] 4. Small OpenSSL script for generating Perfect Forward Secrecy ECDSA key at runtime
- [ ] 5. Have Docker Ubuntu image come from GCR in light of recent Docker Hub hack

**Comment by danehrlich1** [comment]
- [ ] 6. Add `Cloudbuild.yaml` file so that way for every push for at least V2- Ubuntu- Apache new image is tested/build in Google Cloud Build and then pushed to GCR if passing tests

**Comment by danehrlich1** [comment]
Some screenshots of a pretty simple build system using Google Cloud Build.

Anytime there is a push to branch feature/*, the Build trigger will run, which builds the Docker image before shooting it off to Google Container Registry. `CloudBuild.yaml` script could be added, similar to travis-ci.yaml, that directs a lot of test runners, post build logic, etc as well.

Could have additional triggers say that ran through very intensive tests anytime something was merged to master.

image

image

**Comment by csanders-git** [comment]
Realistically dockerhub should/can do this -- the issue right now is that OWASP has some problems with their repo.

**Comment by csanders-git** [comment]
also take a look at the general format i've been using in the newer nginx/apache images
https://github.com/CRS-support/modsecurity-docker/tree/v3/nginx-nginx

**Comment by danehrlich1** [comment]
> also take a look at the general format i've been using in the newer nginx/apache images
> https://github.com/CRS-support/modsecurity-docker/tree/v3/nginx-nginx

1. Oh wow this image is much cooler. I will try to mirror the techniques / syntax you use in this one.
2. I also didn't know Docker Hub added CI. I'll just wait for that. If Kubernetes ever happens, the Google stuff will be handy though.

**Comment by danehrlich1** [comment]
This is still being worked on FYI. I'm working with another person over here: https://github.com/danehrlich1/modsecurity-kubernetes

Will upload my local commits in a couple of days and bring this pull request over.

Also will bring over some of the cool stuff I've seen @csanders-git do with the Nginx docker for sure. Not sure where that repo I posted above will wind up, but hopefully a lot of good work can be done in parallel there, and we can find out where to integrate stuff later.

Ugh very determined to get this done, even if I have to pay contractors to help me. Thanks so much for the patience everyone.

**Comment by fzipi** [comment]
@danehrlich1 Is this still relevant? Do you want to push an update here, or we close?

**Comment by fzipi** [comment]
Hey @danehrlich1!

Do you think this one is still good to try to merge somewho? Or is it covered by last updates?

**Comment by fzipi** [comment]
Closing, no answer from original author.

**Pull request closed without merging**
