### PR TITLE
Revert "feat(nginx): update to 1.22.0 with support for PCRE2"

### PR DESCRIPTION
**Pull request by fzipi**
Reverts coreruleset/modsecurity-docker#121

### CODE REVIEW

**Comment by fzipi** [comment]
This is failing the build, so we revert while @khiemdoan takes a look at why it fails.

**Comment by khiemdoan** [comment]
Hello @fzipi,
Can you provide more detail about the falling? I have checked out my commits, rebuilt them, and got no errors.

```bash
docker build . -f .\v3-nginx\Dockerfile-t modsecurity:nginx
docker build . -f .\v3-nginx\Dockerfile-alpine -t modsecurity:nginx-alpine
```

The github runner also did not fall.

image

I also test the image without any problem.
```bash
docker run -it --rm -p 80:80 -p 443:443 -e BACKEND=http://<an_ip>:8080 modsecurity:nginx-alpine
```

**Comment by fzipi** [comment]
Ugh, it failed in the run, so I went and revert quickly. Let's give it another try 🤷

**Comment by fzipi** [comment]
This was the failing build: https://github.com/coreruleset/modsecurity-docker/actions/runs/2889802276

**Comment by fzipi** [comment]
@kiemdoam After trying a second time, this is the error:
```
  > [linux/arm64 stage-1  2/16] RUN set -eux;     apk add --no-cache         curl-dev         libmaxminddb-dev         libstdc++         libxml2-dev         lmdb-dev         moreutils         tzdata         yajl;     mkdir /etc/nginx/ssl/;     mkdir -p /tmp/modsecurity/data;     mkdir -p /tmp/modsecurity/upload;     mkdir -p /tmp/modsecurity/tmp;     chown -R nginx:nginx /usr/share/nginx /tmp/modsecurity:
#18 16.48   lmdb-dev (no such package):
#18 16.48     required by: world[lmdb-dev]
#18 16.48   yajl (no such package):
#18 16.48     required by: world[yajl]
#18 16.48   perl-io-tty (no such package):
#18 16.48     required by: perl-ipc-run-20200505.0-r1[perl-io-tty]
#18 16.48   perl (no such package):
#18 16.48     required by: moreutils-0.67-r0[perl]
#18 16.48   perl-timedate (no such package):
#18 16.48     required by: moreutils-0.67-r0[perl-timedate]
```
Are you able to fix it today, or we revert again?

**Comment by khiemdoan** [comment]
Hi @fzipi,
I see the falling accidents on Alpine arm64 and these are some packages that are missing. Unfortunately, the runner when making a pull request only runs on amd64.
Please revert it again. I will take more time to solve this problem and I hope we will have better runners to avoid inconsistency between them.

**Comment by fzipi** [comment]
Reverted again in #134 .

**Pull request merged**
