### PR TITLE
feat(core): add more variables

### PR DESCRIPTION
**Pull request by fzipi**
Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>

Adds additional variables:
- `SecDefaultAction` for phase 1 and phase 2.
- `SecAuditLogParts`
- `SecTmpSaveUploadedFiles`

Also, variables are sorted now.

### CODE REVIEW

**Comment by fzipi** [comment]
@franbuehler Need your review here also.

**Comment by franbuehler** [comment]
Until when do we need an approval here?
I would like to test it with a local docker build.

**Comment by fzipi** [comment]
For sure, let me know!

**Review by franbuehler — APPROVED** [review]
I built and tested the v2-apache version locally with MODSEC_AUDIT_LOG_PARTS and it seems to work.

**Pull request merged**
