### PR TITLE
feat(nginx): add support for pcre2

### LINKED ISSUE #120: Add support to PCRE2 in v3
Per https://github.com/SpiderLabs/ModSecurity/pull/2719, we might want to add a new version based on pcre2 only.

As compilation flags change, we need to see if this breaks something or not.

### PR DESCRIPTION
**Pull request by fzipi**
Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>

- this is another try at getting pcre2 in nginx containers.

Fixes #120.

### CODE REVIEW

**Review by theseion — APPROVED** [review]

**Comment by theseion** [comment]
Just so I understand: before this change, PCRE3 was used and after the change, PCRE2 will be used?

**Comment by fzipi** [comment]
I think it is bad naming. The classic pcre version is 8.xx, and pcre2 is the maintained version now, 10.4x or something.

**Comment by theseion** [comment]
That I understand. What I want to know is whether the current version uses PCRE3. Obviously, after the change it will use PCRE2 (hence the `--with-pcre2` flag). If that is true, then this might change the behaviour of the image slightly. Also, why do we still need `libpcre3-dev` if we drop PCRE3?

**Comment by fzipi** [comment]
The current version uses pcre3. Which is pcre v8.39-14 in debian naming (confusing? yes. See https://tracker.debian.org/pkg/pcre3). What is called pcre2, is in fact v10.40 (see https://tracker.debian.org/pkg/pcre2). So, pcre2 > pcre3.

Other than that, dropped that extra line for pcre3-dev.

**Comment by fzipi** [comment]
Well, now I can see it is required.. but not used. Probably because of this https://github.com/SpiderLabs/ModSecurity/blob/82f75dc0ce134c639df6c33bd610519bd4e90e42/configure.ac#L129.

I guess adding it won't hurt?

**Comment by theseion** [comment]
Thanks, now I understand :)

**Review by theseion — DISMISSED** [review]

**Comment by fzipi** [comment]
Last time this failed building on alternative architectures. I'm thinking on having something like #148 implemented before merging this one. OF course, the ultimate case will be when merging to master, but if we can have it working before it will be better.

**Comment by fzipi** [comment]
Ended up adding a new workflow. Trying to create a dynamic matrix for platform, but didn't succeeded.

**Review by theseion — APPROVED** [review]

**Comment by fzipi** [comment]
Now we can test all platforms using a manual step:
image

**Pull request merged**
