### PR TITLE
Set real ip for nginx

### PR DESCRIPTION
**Pull request by LotusAxt**
The apache container has a config to set the trusted proxy address.
However, for nginx I didn't found an equivalent for it.
See https://nginx.org/en/docs/http/ngx_http_realip_module.html for details.

### CODE REVIEW

**Comment by fzipi** [comment]
Is the default client coming from localhost? Or from a docker network internal ip? (didn't verified this)

**Comment by fzipi** [comment]
If the file needs to be pre-processed, we need to add it to the list in the docker-entrypoint.sh.

The PR #105 is supposed to help with this by moving files to templates that generate the actual config files.

**Comment by LotusAxt** [comment]
Ah, I missed that one. On my local installation I added it directly to the default.conf and saw just in the repo that it included the proxy file and moved it quickly... 

On my installation the default IP was the one from the Docker host (172.17.0.1).

**Comment by fzipi** [comment]
@theMiddleBlue Can you review this one?

**Comment by fzipi** [comment]
@theMiddleBlue Can you review this one?

**Comment by theMiddleBlue** [comment]
LGTM, can we just rename the ENV variable with something similar to the config directive `set_real_ip_from` instead of trusted_proxy? Also, what if I need to set IPv4 and IPv6 classes? Is there a way to add multiple `set_real_ip_from` directives and add a `real_ip_recursive on;`?

**Comment by fzipi** [comment]
@LotusAxt Can you make those changes? Something is failing in alpine build also...

**Comment by fzipi** [comment]
@LotusAxt Are you up to solving conflicts and taking on comments?

**Comment by theseion** [comment]
Sorry, messed this up. Will open a new PR.

**Pull request closed without merging**
